all:
	gcc -g -o trie trie.c -std=c99
	gcc -g -o filter filter.c -std=c99
#	gcc -g -o genstr genstr.c
	gcc -g -o compressed_trie compressed_trie.c -std=c99

clean:
	rm -rf trie filter genstr compressed_trie trie_static compressed_trie_static
